### ISSUE TITLE
Speaker pin?

### ISSUE THREAD

**Issue by jvandervyver** [bigtreetech/BIGTREETECH-OCTOPUS-Pro#14]
Hi

What is the pin to which "SPK1" is connected?
If it isn't connected why include a speaker onboard?

**Comment by Budavaril** [comment]
Hi,
Not for controlled by MCU as I guess you thought, so not connected for it. 
But it's connected to a HT7550-2 (SOT23-5) chip to watch the 5V rail voltage is present. If not, then will beeping. 

![Screenshot_20220530-181642_Adobe Acrobat](https://user-images.githubusercontent.com/19350571/171038330-1f0cca56-9ba4-42db-8ba0-2a22d9526a9d.jpg)

![Screenshot_20220530-182005_Chrome](https://user-images.githubusercontent.com/19350571/171038359-61e5ca85-3167-4866-ad7c-1c42c4b344d3.jpg)

**Comment by jvandervyver** [comment]
Wow I really didn't expect such a detailed response.  Thanks for explaining that explains why I hear the beeper when I power down.

> Not for controlled by MCU as I guess you thought

I did
