### ISSUE TITLE
Octopus pro 723 

### ISSUE THREAD

**Issue by jimgineer** [bigtreetech/BIGTREETECH-OCTOPUS-Pro#48]
The Octopus pro V1.1 board with the STM32FH723ZE chip is lacking with clear information. I feel like in an effort to save time any information on that particular board was vaguely put in the margins of manuals with a similar layout.  To me it screams lazy and does not make that part of the build process possible to move forward confidently without stress of ruining the board.

**Comment by PZrk73** [comment]
Unfortunately, these are the realities of this time. The authors are generally reluctant to support the project. There is a circuit for the product. This is no small thing! I'm trying to figure it out by understanding the circuit.

**Comment by Manu512** [comment]
I agree, clear documentation is essential for customers and DIY enthusiasts. If you're looking for specific information

**Comment by bigtreetech** [comment]
The different MCUs share the same pin numbers aside from those mentioned in the readme. The documentation is equally applicable to both.
